### ISSUE TITLE
Can't chdir to '/home/ec2-user/watchmen': No such file or directory

### ISSUE THREAD

**Issue by abhinavkumar940** [iloire/watchmen#77]
It's a fresh install and I am getting this while running
`redis-server redis.conf`

**Comment by kabirbaidhya** [comment]
I'm getting the same issue. 
```
 ➜ redis-server redis.conf 
19847:C 19 Dec 17:48:30.320 # Can't chdir to '/home/ec2-user/watchmen': No such file or directory
```
@iloire I see that this path is hard coded in `redis.conf` file. Shouldn't this file be in `gitignore`? As these values would likely be different for each deployments. 

I think there should be a sample conf file instead something like `redis.example.conf` or `redis.dist.conf` so that users can create their own `redis.conf` file from it depending on their environment.

**Comment by abhinavkumar940** [comment]
You can try `redis-server redis.dev.conf` for a local redis installation

**Comment by abhinavkumar940** [comment]
I am closing it as it worked for me. Feel free to open another issue or comment here if you need further help.
